services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    user: ${DOCKER_USER}
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - UMASK=022
    volumes:
      - ./config:/config
      - /marvin/Videos/TV:/TV
      - /marvin/ultraseedbox/downloads:/home/r0xyd0g/downloads/
    ports:
      - "8989:8989"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
