services:
  pv2mqtt:
    image: ghcr.io/wez/govee2mqtt:latest
    container_name: govee2mqtt
    restart: unless-stopped
    env_file:
      - ./.env
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"
